/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Mar 03 21:55:21 2019. */

#include "hid.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MouseUpdate_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, MouseUpdate, type, type, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MouseUpdate, x, type, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MouseUpdate, y, x, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
